### ISSUE TITLE
"at least 2GB of free, unlimited storage"

### ISSUE THREAD

**Issue by Omar-Aziz** [nextcloud/providers#10]
It's slightly confusing what "at least 2GB of free, unlimited storage" means. It might be better to clarify the "unlimited" part. Does it mean you can store as many times as you want as long as it's <= 2GB?

**Comment by kesselb** [comment]
I guess that should be unmetered. Mind to submit a patch?

**Comment by jospoortvliet** [comment]
Fixed in https://github.com/nextcloud/providers/commit/545ab9e9327ed016895db34b08c64592593320dc
