### ISSUE TITLE
logos should link to website, not to larger logo

### ISSUE THREAD

**Issue by CouldBeThis** [nextcloud/providers#42]
I am not sure if there is a reason why it is like this currently. But conventionally when you click on the logo of a company/organization, it takes you to their website. On this list it takes you to the full size image file for the logo. I am not sure why anyone would want that? 

If the goal is to direct people to hosts so they can use the product, it would be less confusing the usual way.

**Comment by jospoortvliet** [comment]
Yeah, I totally agree, but I don't believe this is possible... the way you do a link in github markdown is this:
```
[link text](link link)
```
And an image is this:
```
![](link to image)
```
If you put any text or a link in the [] part it will show on hover, but it won't change that it links to the image.

**Comment by CouldBeThis** [comment]
ummmm you are going to laugh when you see this:
https://github.com/CouldBeThis/providers

sorry I do not know how to add the change from my fork to yours. I learned once but then I never used it because I don't know how to program... so I forgot. Also it appears that this repo is locked or something so I double don't know how to do it. 

The instructions at the bottom would need to be changed. 

For accessibility IIRC everyone should be adding alt to the images and name to the links.
